import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;
import Banner from '@/components/Banner';
import Footer from '@/components/Footer';
import Header from '@/components/Header';

import "@/styles/main.scss";

export const metadata = {
  title: "Bellify",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Banner />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
